baseURL = "https://shoutinginfrench.com"
languageCode = "en-us"
title = "shoutinginfrench"
theme = "sif-hugo"
introduction = "Developer from Phoenix, AZ"
headshot = "img/headshot.jpg"

## Hugo Built-in Features
disqusShortname = "samrocksc" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Sam Clark"
intro = "A Developer from Phoenix"
description = "A developer of Javascript and Go from Phoenix.  Also DevOps engineer at @iceddev"
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple Portfolio Theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "samrocksc"
instagram = "samrocksc"
linkedin = "samrocksc"
twitter = "samrocksc"
facebook = "samrocksc"
google = "samrocksc"
stackoverflow = "samrocksc"
email = "samrocksc@gmail.com.com"

## Extras
[params.extra]
copyright = "© 2017. Sam Clark. MIT License"
poweredby = true
highlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
  url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "coderag"
    identifier = "coderag"
    weight = 300
    url = "/coderag/"
